- name: Ensure Keycloak is started
  service:
    name: keycloak
    state: started
- name: wait for Keycloak management interface to be available
  wait_for:
    port: "{{ keycloak_management_http_port }}"
    timeout: "{{ keycloak_startup_timeout }}"
- name: create truststore-config.cli command file
  template:
    src: truststore-config.cli.j2
    dest: "{{ keycloak_config_dir }}/truststore-config.cli"
    owner: root
    group: root
    mode: 0600
- name: apply keycloak truststore configuration
  command:
  args:
    argv:
    - "{{ keycloak_jboss_home }}/bin/jboss-cli.sh"
    - --connect
    - --timeout={{ keycloak_jboss_config_connect_timeout }}
    - --command-timeout={{ keycloak_jboss_config_command_timeout }}
    - --file={{ keycloak_config_dir }}/truststore-config.cli
  tags:
  - skip_ansible_lint
- name: clean up jboss-cli-sh command file
  file:
    path: "{{ keycloak_config_dir }}/truststore-config.cli"
    state: absent
